### ISSUE TITLE
update mqadmin tool docs when operate topic

### ISSUE THREAD

**Issue by chenzlalvin** [apache/rocketmq-site#561]
**FEATURE REQUEST**

1. the admin tool docs currently has no update for message types, add the properties.

**Comment by Jimmy01010** [comment]
rocketMQ version：v5.0.0
使用maadmin创建主题时，类型书写似乎被严格限制为大写字母，当我创建Delay类型的主题时，提示我只能在以下集合中取值 
`value is not in set: [UNSPECIFIED, TRANSACTION, FIFO, DELAY, NORMAL]`

当我换成集合中类型单词的大写拼写后，创建成功：
```
[root@data bin]# sh mqadmin updateTopic -n 172.xx.xx.141:9876 -t timed_task -c DefaultCluster -a +message.type=Delay
org.apache.rocketmq.tools.command.SubCommandException: UpdateTopicSubCommand command failed
	at org.apache.rocketmq.tools.command.topic.UpdateTopicSubCommand.execute(UpdateTopicSubCommand.java:198)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:165)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:114)
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: value is not in set: [UNSPECIFIED, TRANSACTION, FIFO, DELAY, NORMAL]
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.createTopic(MQClientAPIImpl.java:401)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.createAndUpdateTopicConfig(DefaultMQAdminExtImpl.java:262)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.createAndUpdateTopicConfig(DefaultMQAdminExt.java:189)
	at org.apache.rocketmq.tools.command.topic.UpdateTopicSubCommand.execute(UpdateTopicSubCommand.java:173)
	... 2 more
[root@data bin]# 
[root@data bin]# sh mqadmin updateTopic -n 172.xx.xx.141:9876 -t timed_task -c DefaultCluster -a +message.type=DELAY
create topic to 172.xx.xx.141:10911 success.
create topic to 172.xx.xx.141:10921 success.
TopicConfig [topicName=timed_task, readQueueNums=8, writeQueueNums=8, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false, attributes={+message.type=DELAY}]
```


我又测试了其他类型（Normal），此与文档中[示例](https://rocketmq.apache.org/zh/docs/featureBehavior/01normalmessage#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)不一致，需要使用大写类型（NORMAL）
